/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: SDC PERFORMANCE™️ (https://sketchfab.com/3Duae)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/animated-robot-sdc-3d127f327a6c4033a32b810b5fb071ed
Title: Animated ROBOT SDC
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useAnimation } from "../context/AnimationContext";

const scene = "/3d/animatedrobotsdc.glb";
const AnimateRobot = ({ ...props }) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(scene);
  console.log("Available animations", animations);
  const { actions } = useAnimations(animations, group);
  const { currentAnimation } = useAnimation();

  useEffect(() => {
    console.log("Current animation:", currentAnimation);

    console.log("Available actions:", actions);
    // Stop all animations first
    Object.values(actions).forEach((action) => action.stop());
    console.log("Actions after stopping:", actions);
    // Play the current animation if it exists
    if (actions[currentAnimation]) {
      actions[currentAnimation].play();
    }

    // Cleanup function to stop animation when component unmounts

    // return () => {
    //   Object.values(actions).forEach((action) => action.stop());
    // };
  }, [currentAnimation, actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Armature_82" rotation={[0, 1.561, 0]}>
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials.Rubber}
                    skeleton={nodes.Object_7.skeleton}
                  />
                  <group name="Doigts_81" />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

// useGLTF.preload('/animatedrobotsdc.glb')
export default AnimateRobot;
